/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset_default from "./assets/alt_default.png";
import _asset_talk from "./assets/alt_talk.png";
import _asset_annoyed from "./assets/alt_annoyed.png";
import _asset_blush from "./assets/alt_blush.png";
import _asset_bored from "./assets/alt_bored.png";
import _asset_concern from "./assets/alt_concern.png";
import _asset_shy from "./assets/alt_shy.png";
import _asset_happy from "./assets/alt_highcharizma.png";
import _asset_model from "!file-loader!./assets/alt.glb";
import _asset_font from "!file-loader!./assets/PFEFFERMEDIAEVAL.OTF";

export const resources = {
    "userscript.js": _js,
    "style.css": _css,
    "assets/alt.glb": _asset_model,
    "assets/PFEFFERMEDIAEVAL.OTF": _asset_font,
    "assets/alt_default.png": _asset_default,
    "assets/alt_talk.png": _asset_talk,
    "assets/alt_annoyed.png": _asset_annoyed,
    "assets/alt_blush.png": _asset_blush,
    "assets/alt_bored.png": _asset_bored,
    "assets/alt_concern.png": _asset_concern,
    "assets/alt_shy.png": _asset_shy,
    "assets/alt_highcharizma.png": _asset_happy
};
