/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "name": "AI Assistant",
    "description": "AI-powered assistant to help generate block code using Inworld API.",
    "credits": [
        {
            "name": "AltMod Team"
        }
    ],
    "settings": [
        {
            "dynamic": true,
            "name": "Inworld API Key (Base64)",
            "id": "apiKey",
            "type": "text",
            "default": "aUhWY0p6Y1p0aXJvZkdyM1d3dVQwMTdKdDFFWXBwbHk6UFZRYjJkS0RjQXpUYkQ1NUg1RzhwdEI1Q0RYOEZHMlhvdE9lRlM2Wk42Y3hUMFJHRDIwYnJkSGVacFFKWW9Rbg=="
        },
        {
            "dynamic": true,
            "name": "Model",
            "id": "model",
            "type": "select",
            "default": "gpt-5",
            "potentialValues": [
                { "id": "gpt-5", "name": "GPT-5" },
                { "id": "gpt-5-mini", "name": "GPT-5-mini" },
                { "id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro" },
                { "id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash" }
            ]
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "userstyles": [
        {
            "url": "style.css"
        }
    ],
    "tags": [
        "recommended"
    ],
    "enabledByDefault": false
};
export default manifest;
